# Continuous integration with travis
language: r
sudo: required



# cache packages to speed up builds
#cache: packages

addons:
  apt:
    packages:
      - libgdal-dev

r_binary_packages:
 - rgdal


r_packages:
 - curl
 - raster 
 - sp
 - xml2
 - grid 
 - gridExtra
 - httr
 - dplyr
 - stringi
 - tidyr
 - covr



after_success:
 - Rscript -e 'library(covr);codecov()'

matrix:
  include:
    - os: linux
      r: release
    - os: osx







